# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T13:40:47+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, RootModel


class Boolean(RootModel[bool]):
    root: bool


class Float(RootModel[float]):
    root: float


class Integer(RootModel[int]):
    root: int


class InvalidNextToken(BaseModel):
    BoxUsage: Optional[Float] = None


class InvalidNumberPredicates(BaseModel):
    BoxUsage: Optional[Float] = None


class InvalidNumberValueTests(BaseModel):
    BoxUsage: Optional[Float] = None


class InvalidParameterValue(BaseModel):
    BoxUsage: Optional[Float] = None


class InvalidQueryExpression(BaseModel):
    BoxUsage: Optional[Float] = None


class Long(RootModel[int]):
    root: int


class MissingParameter(BaseModel):
    BoxUsage: Optional[Float] = None


class NoSuchDomain(BaseModel):
    BoxUsage: Optional[Float] = None


class NumberDomainAttributesExceeded(BaseModel):
    BoxUsage: Optional[Float] = None


class NumberDomainBytesExceeded(BaseModel):
    BoxUsage: Optional[Float] = None


class NumberDomainsExceeded(BaseModel):
    BoxUsage: Optional[Float] = None


class NumberItemAttributesExceeded(BaseModel):
    BoxUsage: Optional[Float] = None


class NumberSubmittedAttributesExceeded(BaseModel):
    BoxUsage: Optional[Float] = None


class NumberSubmittedItemsExceeded(BaseModel):
    BoxUsage: Optional[Float] = None


class RequestTimeout(BaseModel):
    BoxUsage: Optional[Float] = None


class String(RootModel[str]):
    root: str


class TooManyRequestedAttributes(BaseModel):
    BoxUsage: Optional[Float] = None


class UpdateCondition(BaseModel):
    Exists: Optional[Boolean] = None
    Name: Optional[String] = None
    Value: Optional[String] = None


class Action(Enum):
    BatchDeleteAttributes = 'BatchDeleteAttributes'


class Version(Enum):
    field_2009_04_15 = '2009-04-15'


class Action4(Enum):
    BatchPutAttributes = 'BatchPutAttributes'


class Action8(Enum):
    CreateDomain = 'CreateDomain'


class Expected(BaseModel):
    Exists: Optional[Boolean] = None
    Name: Optional[String] = None
    Value: Optional[String] = None


class Action12(Enum):
    DeleteAttributes = 'DeleteAttributes'


class Action16(Enum):
    DeleteDomain = 'DeleteDomain'


class Action20(Enum):
    DomainMetadata = 'DomainMetadata'


class Action24(Enum):
    GetAttributes = 'GetAttributes'


class AttributeNames(RootModel[List[String]]):
    root: List[String]


class Action28(Enum):
    ListDomains = 'ListDomains'


class Action32(Enum):
    PutAttributes = 'PutAttributes'


class Action36(Enum):
    Select = 'Select'


class Attribute(BaseModel):
    AlternateNameEncoding: Optional[String] = None
    AlternateValueEncoding: Optional[String] = None
    Name: String
    Value: String


class AttributeDoesNotExist(BaseModel):
    BoxUsage: Optional[Float] = None


class AttributeList(RootModel[List[Attribute]]):
    root: List[Attribute]


class AttributeNameList(RootModel[List[String]]):
    root: List[String]


class CreateDomainRequest(BaseModel):
    DomainName: String


class DeletableAttribute(BaseModel):
    Name: String
    Value: Optional[String] = None


class DeletableAttributeList(RootModel[List[DeletableAttribute]]):
    root: List[DeletableAttribute]


class DeletableItem(BaseModel):
    Attributes: Optional[DeletableAttributeList] = None
    Name: String


class DeletableItemList(RootModel[List[DeletableItem]]):
    root: List[DeletableItem]


class DeleteAttributesRequest(BaseModel):
    Attributes: Optional[DeletableAttributeList] = None
    DomainName: String
    Expected: Optional[UpdateCondition] = None
    ItemName: String


class DeleteDomainRequest(BaseModel):
    DomainName: String


class DomainMetadataRequest(BaseModel):
    DomainName: String


class DomainMetadataResult(BaseModel):
    AttributeNameCount: Optional[Integer] = None
    AttributeNamesSizeBytes: Optional[Long] = None
    AttributeValueCount: Optional[Integer] = None
    AttributeValuesSizeBytes: Optional[Long] = None
    ItemCount: Optional[Integer] = None
    ItemNamesSizeBytes: Optional[Long] = None
    Timestamp: Optional[Integer] = None


class DomainNameList(RootModel[List[String]]):
    root: List[String]


class DuplicateItemName(BaseModel):
    BoxUsage: Optional[Float] = None


class GetAttributesRequest(BaseModel):
    AttributeNames: Optional[AttributeNameList] = None
    ConsistentRead: Optional[Boolean] = None
    DomainName: String
    ItemName: String


class GetAttributesResult(BaseModel):
    Attributes: Optional[AttributeList] = None


class Item(BaseModel):
    AlternateNameEncoding: Optional[String] = None
    Attributes: AttributeList
    Name: String


class ItemList(RootModel[List[Item]]):
    root: List[Item]


class ListDomainsRequest(BaseModel):
    MaxNumberOfDomains: Optional[Integer] = None
    NextToken: Optional[String] = None


class ListDomainsResult(BaseModel):
    DomainNames: Optional[DomainNameList] = None
    NextToken: Optional[String] = None


class ReplaceableAttribute(BaseModel):
    Name: String
    Replace: Optional[Boolean] = None
    Value: String


class ReplaceableAttributeList(RootModel[List[ReplaceableAttribute]]):
    root: List[ReplaceableAttribute]


class ReplaceableItem(BaseModel):
    Attributes: ReplaceableAttributeList
    Name: String


class ReplaceableItemList(RootModel[List[ReplaceableItem]]):
    root: List[ReplaceableItem]


class SelectRequest(BaseModel):
    ConsistentRead: Optional[Boolean] = None
    NextToken: Optional[String] = None
    SelectExpression: String


class SelectResult(BaseModel):
    Items: Optional[ItemList] = None
    NextToken: Optional[String] = None


class Items(RootModel[List[DeletableItem]]):
    root: List[DeletableItem]


class Items1(RootModel[List[ReplaceableItem]]):
    root: List[ReplaceableItem]


class Attributes(RootModel[List[DeletableAttribute]]):
    root: List[DeletableAttribute]


class Attributes1(RootModel[List[ReplaceableAttribute]]):
    root: List[ReplaceableAttribute]


class BatchDeleteAttributesRequest(BaseModel):
    DomainName: String
    Items: DeletableItemList


class BatchPutAttributesRequest(BaseModel):
    DomainName: String
    Items: ReplaceableItemList


class PutAttributesRequest(BaseModel):
    Attributes: ReplaceableAttributeList
    DomainName: String
    Expected: Optional[UpdateCondition] = None
    ItemName: String
